[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python start_railway.py"
healthcheckPath = "/status"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments.production]
PYTHON_VERSION = "3.11"
PORT = "8000"

